export const teams = [
    {'name': 'Charlton', 'code': 'CH'},
    {'name': 'Chelsea', 'code': 'CH'},
    {'name': 'Coventry', 'code': 'CO'},
    {'name': 'Derby', 'code': 'DE'},
    {'name': 'Leeds', 'code': 'LE'},
    {'name': 'Leicester', 'code': 'LE'},
    {'name': 'Liverpool', 'code': 'LI'},
    {'name': 'Sunderland', 'code': 'SU'},
    {'name': 'Tottenham', 'code': 'TO'},
    {'name': 'Man United', 'code': 'MU'},
    {'name': 'Arsenal', 'code': 'AR'},
    {'name': 'Bradford', 'code': 'BR'},
    {'name': 'Ipswich', 'code': 'IP'},
    {'name': 'Middlesbrough', 'code': 'MI'},
    {'name': 'Everton', 'code': 'EV'},
    {'name': 'Man City', 'code': 'MC'},
    {'name': 'Newcastle', 'code': 'NE'},
    {'name': 'Southampton', 'code': 'SO'},
    {'name': 'West Ham', 'code': 'WH'},
    {'name': 'Aston Villa', 'code': 'AV'},
    {'name': 'Bolton', 'code': 'BO'},
    {'name': 'Blackburn', 'code': 'BL'},
    {'name': 'Fulham', 'code': 'FU'},
    {'name': 'Birmingham', 'code': 'BI'},
    {'name': 'West Brom', 'code': 'WB'},
    {'name': 'Portsmouth', 'code': 'PO'},
    {'name': 'Wolves', 'code': 'WO'},
    {'name': 'Norwich', 'code': 'NO'},
    {'name': 'Crystal Palace', 'code': 'CP'},
    {'name': 'Wigan', 'code': 'WI'},
    {'name': 'Reading', 'code': 'RE'},
    {'name': 'Sheffield United', 'code': 'SU'},
    {'name': 'Watford', 'code': 'WA'},
    {'name': 'Hull', 'code': 'HU'},
    {'name': 'Stoke', 'code': 'ST'},
    {'name': 'Burnley', 'code': 'BU'},
    {'name': 'Blackpool', 'code': 'BL'},
    {'name': 'QPR', 'code': 'QP'},
    {'name': 'Swansea', 'code': 'SW'},
    {'name': 'Cardiff', 'code': 'CA'},
    {'name': 'Bournemouth', 'code': 'BO'},
    {'name': 'Brighton', 'code': 'BR'},
    {'name': 'Huddersfield', 'code': 'HU'},
    {'name': 'Brentford', 'code': 'BR'}
    ]